<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
    /**
     * @param \DateTime $start
     * @param \DateTime $end
     * @return array
     */
    public function findRangeDate(\DateTime $start, \DateTime $end){
        return $this->getEntityManager()
                    ->createQueryBuilder()
                    ->select('t')
                    ->from(Transaction::class, 't')
                    ->where('t.requestDate > :start')
                    ->andWhere('t.requestDate < :end')
                    ->setParameters(['start' => $start, 'end' => $end])
                    ->getQuery()
                    ->getResult();

    }
}
